### ISSUE TITLE
html elements update too often when nothing happens

### ISSUE THREAD

**Issue by dimart** [scalacenter/scastie#282]
![](https://dr5mo5s7lqrtc.cloudfront.net/items/2u3w2l0Q0I1F2B0X1y3O/Screen%20Recording%202017-07-21%20at%2005.01%20PM.gif)

**Comment by dimart** [comment]
this happens every second:
![](https://dr5mo5s7lqrtc.cloudfront.net/items/293L0S1B2Q3L2D1Z1P37/Image%202017-07-21%20at%205.18.51%20PM.png)

**Comment by dimart** [comment]
#202 and #209 may be useful

**Comment by MasseGuillaume** [comment]
I don't know what I have changed but this one seems fixed now. Try on scastie.scala-lang.org

**Comment by dimart** [comment]
@MasseGuillaume nope, it still happens on scastie.scala-lang.org
I've just found out that it stops if you comment editor.refresh(). Everything seems to be working without this line. Kind of strange. Are you sure we need to run it so often?

**Comment by MasseGuillaume** [comment]
This line is called all the time: https://github.com/scalacenter/scastie/blob/161d3f1a90de3bfc981383878351778095a4db82/client/src/main/scala/com.olegych.scastie.client/components/Editor.scala#L815

**Comment by MasseGuillaume** [comment]
@dimart This is the next thing I do tomorrow morning

https://github.com/scalacenter/scastie/projects/1
