### ISSUE TITLE
“ReferenceError: ScastiePlaygroundMain is not defined” error

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scastie#347]
/cc @julienrf

**Comment by OlegYch** [comment]
should be fixed now

**Comment by julienrf** [comment]
I still get the error :-/

https://scastie.scala-lang.org/cCPFF0MaRkWxtCnluforBA

**Comment by OlegYch** [comment]
@julienrf in this case this is because you're running without worksheet mode on, this is not supported atm for scala.js

**Comment by julienrf** [comment]
Thanks!
